### ISSUE TITLE
ui界面hook问题

### ISSUE THREAD

**Issue by za123** [coolzilj/DouyinHooker#1]
XposedHelpers.findAndHookMethod(clazz, "share", aweme, String::class.java, Boolean::class.java, object : XC_MethodHook() {
                                override fun beforeHookedMethod(param: MethodHookParam) {
                                    Log.d(TAG, "Hook before share.")
                                    Log.d(TAG, "Param[0]: ${param.args[0]}\nParam[1]: ${param.args[1]}\nParam[2]: ${param.args[2]}")
                                    shareObj = param.thisObject as Any
                                }
                            }) 请问hook是这个地方吗

**Comment by za123** [comment]
此外 能给个hook ui界面添加一个图标的例子么

**Comment by coolzilj** [comment]
不知道你想问什么。
所有 hook 都在 https://github.com/coolzilj/DouyinHooker/blob/master/app/src/main/java/me/liujin/douyinhooker/DouyinHook.kt 
这个文件里。

基础问题请自行搜索安卓教程
